version: '2' 
services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:50070
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.7.1-java8
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    ports:
      - "8089:8089"
  historyserver:
    image: bde2020/hadoop-historyserver:1.1.0-hadoop2.7.1-java8
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  nodemanager1:
    image: bde2020/hadoop-nodemanager:1.1.0-hadoop2.7.1-java8
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
  datanode1:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    container_name: datanode1
    depends_on: 
      - namenode
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  datanode2:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    container_name: datanode2
    depends_on: 
      - namenode
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  hue:
    image: bde2020/hdfs-filebrowser:3.11
    environment:
      - NAMENODE_HOST=namenode
    ports:
      - 8088:8088
    depends_on:
      - namenode
      - datanode1
      - datanode2
  jupyterlab:
    image: andreper/jupyterlab:2.1.4-spark-2.4.4
    container_name: jupyterlab
    ports:
      - 8888:8888
    env_file:
      - ./hadoop.env
  spark-master:
    image: andreper/spark-master:2.4.4-hadoop-2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop.env
  spark-worker-1:
    image: andreper/spark-worker:2.4.4-hadoop-2.7
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=12g
    ports:
      - 8081:8081
    depends_on:
      - spark-master
  spark-worker-2:
    image: andreper/spark-worker:2.4.4-hadoop-2.7
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=12g
    ports:
      - 8082:8081
    env_file:
      - ./hadoop.env
    depends_on:
      - spark-master
volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_historyserver:

